plugins:
  - search
  - autorefs
site_name: WildcoreDMS
theme:
  language: en
  name: material
  logo: assets/wildcore_logo.png
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
#    - name: Українська
#      link: /uk/
#      lang: uk

nav:
  - "Home": index.md
  - "Pre requirements": requirements.md
  - "Install & Updating":
     - "Installation": install.md
     - "Updating": update.md
  - "Web interface":
      - "After install": web-after-install.md
      - "Use proxy": web-interface/use-proxy.md
  - "Console": cli/index.md
  - "Working with equipment": system/how_works_with_device.md
  - "Hardware Poller": system/poller.md
  - "About components": components/index.md
  - "Components":
    - "Events": components/events.md
    - "Notifications": components/notifications.md
    - "Autodiscovery": components/autodiscovery.md
    - "OLTs": components/olts.md
    - "OLTs control": components/olts_control.md
    #- "ICMP pinger": components/pinger.md
    #- "Import Prometheus": components/prometheus_wrapper.md
    #- "Search devices": components/search_device.md
    #- "Switches": components/switches.md
    #- "D-Link Switches": components/dlink_switches.md
    #- "Edge-Core Switches": components/edgecore_switches.md
    #- "Huawei switches": components/huawei_switches.md
    #- "BDcom olts": components/bdcom_olts.md
    #- "C-Data Olts": components/c_data_interfaces.md
    #- "ZTE Olts": components/zte_olts.md
    #- "Mikrotik routers": components/router_os.md
    - "Registration of ONU on ZTE": components/zte_unregistered_onts.md
    - "Billing NoDeny Plus": components/nodeny_plus.md
    #- "Registration of ONU on Huawei": components/huawei_onts_registration.md
  - "API":
      - "Main": api/index.md
      - "Examples": api/examples.md
      - "Objects":
          - "General responses": api/objects/objects.md
          - "Modules(diagnostic)": api/objects/module_responses.md

  - "WCA-TOOL utility": wca-tool/index.md
  - "Troubleshooting": troubleshooting/index.md
  - "Contacts": contact/contacts.md
  - "Changelog":
      - "0.17 (05.2023)": changelogs/0.17.md
