plugins:
  - search
  - autorefs
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - attr_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
        permalink: ➧
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

site_name: WildcoreDMS wiki
repo_url: https://github.com/wildcore-dms/wiki
theme:
  language: uk
  name: material
  features:
    - navigation.footer
    - content.code.copy
  logo: assets/wildcore_logo.png

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Українська
      link: /uk/
      lang: uk
nav:
  - "Головна": index.md

  - "Функціонал": features/main.md

  - "Встановлення та оновлення":
     - "Початок роботи": installation-and-updating/getting-started.md
     - "Оновлення": installation-and-updating/update.md
     - "Системні вимоги": installation-and-updating/requirements.md

  - "Веб-інтерфейс":
      - "Вигляд": web-interface/main.md
      - "Після встановлення": web-interface/web-after-install.md
      - "Огляд Дешборду": web-interface/dashboard-overview.md
      - "Огляд Параметрів аккаунту": web-interface/user-settings-overview.md
      - "Використання проксі": web-interface/use-proxy.md

  - "Консоль": cli/index.md

  - "Робота з облананням": system/working-with-hardware.md

  - "Опитувач обладнанная": system/poller.md

  - "Про компоненти": components/index.md

  - "Компоненти":
      - "Макроси":
        - "З чого почати": components/macros/getting-started.md
        - "Опції типів параметрів": components/macros/parameter_type_options.md
        - "Спеціальні команди Шаблонів": components/macros/special-commands.md
        - "Приклади шаблонів Twig": components/macros/twig-examples.md
      - "Події": components/events.md
      - "Сповіщення": components/notifications.md
      - "Autodiscovery": components/autodiscovery.md
      - "ОЛТи": components/olts.md
      - "Управління ОЛТ": components/olts_control.md
      - "Реєстрація ОНУ":
        - "Початок роботи": components/onts-registration/getting-started.md
        - "Створення макроса шаблону рєєстрації": components/onts-registration/registration-macro.md
        - "Рєєстрація ОНУ на сторінці пристрою" : components/onts-registration/registration-device.md
      - "Бекапи конфігурації": components/oxidized.md
      - "Пристрої моніторингу": components/sensors.md
      - "Біллінг MikBill": components/mikbill_integration.md
      - "Біллінг NoDeny Plus": components/nodeny_plus.md

  - "АПІ":
      - "Головна": api/index.md
      - "Приклади": api/examples.md
      - "Об'єкти":
          - "Відповіть АПІ": api/objects/objects.md
          - "Відповіть модулів (дігностика)": api/objects/module_responses.md

  - "WCA-TOOL": wca-tool/index.md

  - "Вирішення проблем": 
    - "WildcoreDMS": troubleshooting/agent/general.md
    - "Обладнання":
      - "OLT":
        - "BDCOM": troubleshooting/device-specific/olts/bdcom.md
        - "C-Data": troubleshooting/device-specific/olts/c-data.md
        - "Huawei": troubleshooting/device-specific/olts/huawei.md

      # ! DO NOT DELETE ! #
        # - "GCOM": troubleshooting/device-specific/olts/gcom.md
        # - "V-Solution": troubleshooting/device-specific/olts/v-solution.md
        # - "ZTE": troubleshooting/device-specific/olts/zte.md
      # - "Switches":
      #   - "Alcatel": troubleshooting/device-specific/switches/alcatel.md
      #   - "Cisco": troubleshooting/device-specific/switches/cisco.md
      #   - "Dell": troubleshooting/device-specific/switches/dell.md
      #   - "D-link": troubleshooting/device-specific/switches/d-link.md
      #   - "Edge-core": troubleshooting/device-specific/switches/edge-core.md
      #   - "Eltex": troubleshooting/device-specific/switches/eltex.md
      #   - "HP": troubleshooting/device-specific/switches/hp.md
      #   - "Huawei": troubleshooting/device-specific/switches/huawei.md
      #   - "Juniper": troubleshooting/device-specific/switches/juniper.md
      #   - "Mikrotik": troubleshooting/device-specific/switches/mikrotik.md
      #   - "Raisecom": troubleshooting/device-specific/switches/raisecom.md
      #   - "TP-Link": troubleshooting/device-specific/switches/tp-link.md
      #   - "UBNT": troubleshooting/device-specific/switches/ubnt.md
      # - "Routers":
      #     - "Mikrotik": troubleshooting/device-specific/routers/mikrotik.md
      # - "Sensors":
      #     - "Ping3": troubleshooting/device-specific/sensors/ping3.md
    - "Зовнішні застосунки":
      # - "Grafana": troubleshooting/external-apps/grafana.md
      - "Prometheus": troubleshooting/external-apps/prometheus.md
    # ! DO NOT DELETE ! #

  - "FAQ": faq.md

  - "Вартість": prices.md

  - "Контакти": contact/contacts.md

  - "Історія версій": changelog.md
  - "Список обладнання": https://htmlpreview.github.io/?https://raw.githubusercontent.com/meklis/switcher-core/master/docs/device_info.html
  
