site_name: WildcoreDMS wiki
repo_url: https://github.com/wildcore-dms/wiki
theme:
  language: uk
  name: material
  features:
    - navigation.footer
  logo: assets/wildcore_logo.png

plugins:
  - search
  - autorefs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - attr_list

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Українська
      link: /uk/
      lang: uk
nav:
  - "Головна": index.md
  - "Функціонал": features/main.md
  - "Встановлення та оновлення":
     - "Початок роботи": installation-and-updating/getting-started.md
     - "Оновлення": installation-and-updating/update.md
     - "Системні вимоги": installation-and-updating/requirements.md
  - "Веб-інтерфейс":
      - "Вигляд": web-interface/main.md
      - "Після встановлення": web-after-install.md
      - "Використання проксі": web-interface/use-proxy.md
  - "Консоль": cli/index.md
  - "Робота з облананням": system/how_works_with_device.md
  - "Опитувач обладнанная": system/poller.md
  - "Про компоненти": components/index.md
  - "Компоненти":
      - "Макроси":
        - "З чого почати": components/macros/getting-started.md
        - "Опції типів параметрів": components/macros/parameter_type_options.md
        - "Приклади шаблонів Twig": components/macros/twig-examples.md
      - "Події": components/events.md
      - "Сповіщення": components/notifications.md
      - "Autodiscovery": components/autodiscovery.md
      - "ОЛТи": components/olts.md
      - "Управління ОЛТ": components/olts_control.md
      - "Бекапи конфігурації": components/oxidized.md
      #- "ICMP pinger": components/pinger.md
      #- "Import Prometheus": components/prometheus_wrapper.md
      #- "Search devices": components/search_device.md
      #- "Switches": components/switches.md
      #- "D-Link Switches": components/dlink_switches.md
      #- "Edge-Core Switches": components/edgecore_switches.md
      #- "Huawei switches": components/huawei_switches.md
      #- "BDcom olts": components/bdcom_olts.md
      #- "C-Data Olts": components/c_data_interfaces.md
      #- "ZTE Olts": components/zte_olts.md
      #- "Mikrotik routers": components/router_os.md
      - "Реєстрація ОНУ": components/onts_registration.md
      - "Пристрої моніторингу": components/sensors.md
      - "Біллінг MikBill": components/mikbill_integration.md
      - "Біллінг NoDeny Plus": components/nodeny_plus.md
    #- "Registration of ONU on Huawei": components/huawei_onts_registration.md
  - "АПІ":
      - "Головна": api/index.md
      - "Приклади": api/examples.md
      - "Об'єкти":
          - "Відповіть АПІ": api/objects/objects.md
          - "Відповіть модулів (дігностика)": api/objects/module_responses.md

  - "WCA-TOOL": wca-tool/index.md
  - "Вирішення проблем": troubleshooting/index.md
  - "Вартість": prices.md
  - "Контакти": contact/contacts.md
  - "Історія версій": changelog.md
