site_name: WildcoreDMS документація
theme:
  name: material
  logo: assets/logo.png
extra:
  alternate:
    - name: Русский
      link: /ru/
      lang: ru
    - name: Українська
      link: /ua/
      lang: ua

nav:
  - "Головна": index.md
  - "Цінова політика": cost.md
  - "Початок роботи":
     - "Вимоги": requirements.md
     - "Встановлення": install.md
     - "Початок роботи з веб": basic-settings.md
  - "Веб-інтерфейс":
      - "Вступ": web-interface/index.md
      - "Використання проксі": web-interface/use-proxy.md
  - "Термінал":
      - "Про термінал": cli/index.md
  - "Модульність":
      - "Про компоненти": components/index.md
      - "Компоненти":
        - "Сповіщення": components/alerts.md
        - "Автовиявлення": components/autodiscovery.md
        - "Діагностика": components/diagnostic.md
        - "Події": components/events.md
        - "Історія FDB": components/fdb_history.md
        - "ICMP-пінгер": components/pinger.md
        - "Імпорт Prometheus": components/prometheus_wrapper.md
        - "Пошук пристроїв": components/search_device.md
        - "Світчі": components/switches.md
        - "Світчі D-Link": components/dlink_switches.md
        - "Світчі Edge-Core": components/edgecore_switches.md
        - "Cвітчі Huawei": components/huawei_switches.md
        - "Олти BDcom": components/bdcom_olts.md
        - "Олти C-Data": components/c_data_interfaces.md
        - "Олти ZTE": components/zte_olts.md
        - "Роутери Mikrotik": components/router_os.md
        - "Реєстрація ОНУ": components/zte_unregistered_onts.md
  - "Утиліта wca-tool":  wca-tool/index.md
  - "Вирішення проблем": troubleshooting/index.md
  - "Контакти": contact/contacts.md
