site_name: WildcoreDMS документация
theme:
  language: ru
  name: material
  logo: assets/logo.png
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Українська
      link: /uk/
      lang: uk
    - name: български
      link: /bg/
    - name: Русский
      link: /ru/
      lang: ru

nav:
  - "Главная": index.md
  - "Начало работы":
     - "Требования": requirements.md
     - "Установка": install.md
     - "Начало работы с веб": basic-settings.md
  - "Веб-интерфейс":
      - "Введение": web-interface/index.md
      - "Использование прокси": web-interface/use-proxy.md
  - "Консоль": cli/index.md
  - "Работа с оборудованием": system/how_works_with_device.md
  - "Опросчик оборудования": system/poller.md
  - "О компонентах": components/index.md
  - "Компоненты":
    - "События": components/events.md
    - "Уведомления": components/notifications.md
    - "Автообнаружение": components/autodiscovery.md
    - "Олты": components/olts.md
    #- "История FDB": components/fdb_history.md
    #- "ICMP-пингер": components/pinger.md
    #- "Импорт Prometheus": components/prometheus_wrapper.md
    #- "Поиск устройств": components/search_device.md
    #- "Свитчи": components/switches.md
    #- "Свитчи D-Link": components/dlink_switches.md
    #- "Свитчи Edge-Core": components/edgecore_switches.md
    #- "Cвитчи Huawei": components/huawei_switches.md
    #- "Олты BDcom": components/bdcom_olts.md
    #- "Олты ZTE": components/zte_olts.md
    #- "Роутеры Mikrotik": components/router_os.md
    - "Регистрация ОНУ на ZTE": components/zte_unregistered_onts.md
    #- "Регистрация ОНУ на Huawei": components/huawei_onts_registration.md
  - "Утилита wca-tool":  wca-tool/index.md
  - "Решение проблем": troubleshooting/index.md
  - "Контакты": contact/contacts.md
  - "Стоимость": cost.md
