site_name: WildcoreDMS документация
theme:
  language: ru
  name: material
  logo: assets/logo.png
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Українська
      link: /uk/
      lang: uk
    - name: български
      link: /bg/
      lang: uk
    - name: Русский
      link: /ru/
      lang: ru

nav:
  - "У дома": index.md
  - "Начало на работа":
     - "Изисквания": requirements.md
     - "Инсталация": install.md
     - "Начало работы с веб": basic-settings.md
  - "Първи стъпки в мрежата":
      - "Въведение": web-interface/index.md
      - "Използване на прокси": web-interface/use-proxy.md
  - "Конзола": cli/index.md
  - "Работа с оборудване": system/how_works_with_device.md
  - "Разпитващо оборудване": system/poller.md
  - "О компонентах": components/index.md
  - "Относно компонентите":
    - "Разработки": components/events.md
    - "Известия": components/notifications.md
    - "Автоматично откриване": components/autodiscovery.md
    #- "История FDB": components/fdb_history.md
    #- "ICMP-пингер": components/pinger.md
    #- "Импорт Prometheus": components/prometheus_wrapper.md
    #- "Поиск устройств": components/search_device.md
    #- "Свитчи": components/switches.md
    #- "Свитчи D-Link": components/dlink_switches.md
    #- "Свитчи Edge-Core": components/edgecore_switches.md
    #- "Cвитчи Huawei": components/huawei_switches.md
    #- "Олты BDcom": components/bdcom_olts.md
    #- "Олты C-Data": components/c_data_interfaces.md
    #- "Олты ZTE": components/zte_olts.md
    #- "Роутеры Mikrotik": components/router_os.md
    - "Регистрация на ONU на ZTE": components/zte_unregistered_onts.md
    #- "Регистрация ОНУ на Huawei": components/huawei_onts_registration.md
  - "wca-tool полезност":  wca-tool/index.md
  - "Решение на проблеми": troubleshooting/index.md
  - "Контакти": contact/contacts.md
  - "Цена": cost.md
